### ISSUE TITLE
InvalidModelEntity error thrown when adding relations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1009]
**Describe the bug**

So my dates and tickets editor refactor has a component that allows you to set relations between dates and tickets.
The component is wrapped in `withSelect()` and `withDispatch()` HOCs for connecting to the EE data stores.
Here is the `withDispatch()` HOC that provides callbacks for the component to use for adding and removing relations:

> plz note: `DATETIME`, and `TICKET` are constants I use for the corresponding model names

```js
	withDispatch( ( dispatch ) => {
		const addTickets = async ( date, tickets ) => {
			if ( isModelEntityOfModel( date, DATETIME ) ) {
				const {
					createRelation,
					persistRelationsForEntityIdAndRelation,
					resolveRelationRecordForRelation,
				} = dispatch( 'eventespresso/core' );
				if ( Array.isArray( tickets ) ) {
					tickets.forEach( ( ticket ) => {
						if ( isModelEntityOfModel( ticket, TICKET ) ) {
							createRelation( DATETIME, date.id, TICKET, ticket );
							resolveRelationRecordForRelation(
								date,
								TICKET,
								ticket.id
							);
						}
					} );
				}
				persistRelationsForEntityIdAndRelation(
					DATETIME,
					date.id,
					TICKET
				);
			}
		};
		const removeTickets = async ( date, tickets ) => {
			if ( isModelEntityOfModel( date, DATETIME ) ) {
				const {
					removeRelationForEntity,
					persistRelationsForEntityIdAndRelation,
				} = dispatch( 'eventespresso/core' );
				if ( Array.isArray( tickets ) ) {
					tickets.forEach( ( ticket ) => {
						if ( isModelEntityOfModel( ticket, TICKET ) ) {
							removeRelationForEntity( DATETIME,
								date.id,
								TICKET,
								ticket.id
							);
						}
					} );
				}
				persistRelationsForEntityIdAndRelation(
					DATETIME,
					date.id,
					TICKET,
					false
				);
			}
		};
		return { addTickets, removeTickets };
	} ),
```

Both callbacks receive a single datetime entity and array of ticket entities, which are all validated using `isModelEntityOfModel()` before attempting to do anything with them.
The `removeTickets()` callback works correctly, but `addTickets()` produces the following error whenever it is called:

```js
create-entities-generators.js:108
Uncaught (in promise) InvalidModelEntity: Invalid model entity instance provided.Invalid type provided.
receiveEntityIdAndResolve expects an instance of BaseEntity
    at assertIsModelEntity (/assets/dist/ee-data-stores.941e17a4e390f11c23bc.dist.js:781:11)
    at receiveEntityAndResolve$ (/assets/dist/ee-data-stores.941e17a4e390f11c23bc.dist.js:715:11)
    at tryCatch (/assets/dist/ee-data-stores.941e17a4e390f11c23bc.dist.js:14478:40)
    at Generator.invoke [as _invoke] (/assets/dist/ee-data-stores.941e17a4e390f11c23bc.dist.js:14704:22)
    at Generator.prototype.(anonymous function) [as next] (/assets/dist/ee-data-stores.941e17a4e390f11c23bc.dist.js:14530:21)
    at http://local.wordpress.test/wp-includes/js/dist/redux-routine.js?ver=3.0.3:363:55
    at iterate (http://local.wordpress.test/wp-includes/js/dist/redux-routine.js?ver=3.0.3:382:24)
    at runtime (http://local.wordpress.test/wp-includes/js/dist/redux-routine.js?ver=3.0.3:404:5)
    at http://local.wordpress.test/wp-includes/js/dist/redux-routine.js?ver=3.0.3:854:14
    at new Promise (<anonymous>)
```

So there is either a mistake in the documentation for one of the following functions:

- createRelation
- persistRelationsForEntityIdAndRelation
- resolveRelationRecordForRelation,

and I need to pass an entity instead of an ID, or there is sort of bug somewhere in the call stack that is not supplying the correct data for another function.

Here is the rest of the call stack/error output that appears below the above error details:

  | InvalidModelEntity | @ | invalid-model-entity.js:21
-- | -- | -- | --
  | assertIsModelEntity | @ | create-entities-generators.js:108
  | receiveEntityAndResolve$ | @ | create-entities-generators.js:55
  | tryCatch | @ | runtime.js:62
  | invoke | @ | runtime.js:288
  | prototype.(anonymous function) | @ | runtime.js:114
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:363
  | iterate | @ | redux-routine.js?ver=3.0.3:382
  | runtime | @ | redux-routine.js?ver=3.0.3:404
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:854
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:853
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:895
  | (anonymous) | @ | data.js?ver=4.2.0:727
  | DISPATCH | @ | base-controls.js:142
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:825
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:378
  | next | @ | redux-routine.js?ver=3.0.3:377
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:369
  | iterate | @ | redux-routine.js?ver=3.0.3:382
  | runtime | @ | redux-routine.js?ver=3.0.3:404
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:854
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:853
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:895
  | (anonymous) | @ | data.js?ver=4.2.0:727
  | (anonymous) | @ | dates-and-tickets-manager.js:604
  | _callee$ | @ | dates-and-tickets-manager.js:602
  | tryCatch | @ | runtime.js:62
  | invoke | @ | runtime.js:288
  | prototype.(anonymous function) | @ | runtime.js:114
  | asyncGeneratorStep | @ | asyncToGenerator.js:5
  | _next | @ | asyncToGenerator.js:27
  | (anonymous) | @ | asyncToGenerator.js:34
  | F | @ | _export.js:36
  | (anonymous) | @ | asyncToGenerator.js:23
  | addTickets | @ | dates-and-tickets-manager.js:590
  | proxyDispatch | @ | data.js?ver=4.2.0:1936
  | (anonymous) | @ | dates-and-tickets-manager.js:96
  | onClick | @ | dates-and-tickets-manager.js:456
  | callCallback | @ | react-dom.js?ver=16.6.3:143
  | invokeGuardedCallbackDev | @ | react-dom.js?ver=16.6.3:193
  | invokeGuardedCallback | @ | react-dom.js?ver=16.6.3:250
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.js?ver=16.6.3:264
  | executeDispatch | @ | react-dom.js?ver=16.6.3:555
  | executeDispatchesInOrder | @ | react-dom.js?ver=16.6.3:577
  | executeDispatchesAndRelease | @ | react-dom.js?ver=16.6.3:674
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.js?ver=16.6.3:682
  | forEachAccumulated | @ | react-dom.js?ver=16.6.3:656
  | runEventsInBatch | @ | react-dom.js?ver=16.6.3:810
  | runExtractedEventsInBatch | @ | react-dom.js?ver=16.6.3:818
  | handleTopLevel | @ | react-dom.js?ver=16.6.3:4923
  | batchedUpdates$1 | @ | react-dom.js?ver=16.6.3:19056
  | batchedUpdates | @ | react-dom.js?ver=16.6.3:2148
  | dispatchEvent | @ | react-dom.js?ver=16.6.3:5002
  | interactiveUpdates$1 | @ | react-dom.js?ver=16.6.3:19111
  | interactiveUpdates | @ | react-dom.js?ver=16.6.3:2167
  | dispatchInteractiveEvent | @ | react-dom.js?ver=16.6.3:4979
  | Promise.then (async) |   |  
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:829
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:378
  | next | @ | redux-routine.js?ver=3.0.3:377
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:369
  | iterate | @ | redux-routine.js?ver=3.0.3:382
  | runtime | @ | redux-routine.js?ver=3.0.3:404
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:854
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:853
  | (anonymous) | @ | redux-routine.js?ver=3.0.3:895
  | (anonymous) | @ | data.js?ver=4.2.0:727
  | (anonymous) | @ | dates-and-tickets-manager.js:604
  | _callee$ | @ | dates-and-tickets-manager.js:602
  | tryCatch | @ | runtime.js:62
  | invoke | @ | runtime.js:288
  | prototype.(anonymous function) | @ | runtime.js:114
  | asyncGeneratorStep | @ | asyncToGenerator.js:5
  | _next | @ | asyncToGenerator.js:27
  | (anonymous) | @ | asyncToGenerator.js:34
  | F | @ | _export.js:36
  | (anonymous) | @ | asyncToGenerator.js:23
  | addTickets | @ | dates-and-tickets-manager.js:590
  | proxyDispatch | @ | data.js?ver=4.2.0:1936
  | (anonymous) | @ | dates-and-tickets-manager.js:96
  | onClick | @ | dates-and-tickets-manager.js:456
  | callCallback | @ | react-dom.js?ver=16.6.3:143
  | invokeGuardedCallbackDev | @ | react-dom.js?ver=16.6.3:193
  | invokeGuardedCallback | @ | react-dom.js?ver=16.6.3:250
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.js?ver=16.6.3:264
  | executeDispatch | @ | react-dom.js?ver=16.6.3:555
  | executeDispatchesInOrder | @ | react-dom.js?ver=16.6.3:577
  | executeDispatchesAndRelease | @ | react-dom.js?ver=16.6.3:674
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.js?ver=16.6.3:682
  | forEachAccumulated | @ | react-dom.js?ver=16.6.3:656
  | runEventsInBatch | @ | react-dom.js?ver=16.6.3:810
  | runExtractedEventsInBatch | @ | react-dom.js?ver=16.6.3:818
  | handleTopLevel | @ | react-dom.js?ver=16.6.3:4923
  | batchedUpdates$1 | @ | react-dom.js?ver=16.6.3:19056
  | batchedUpdates | @ | react-dom.js?ver=16.6.3:2148
  | dispatchEvent | @ | react-dom.js?ver=16.6.3:5002
  | interactiveUpdates$1 | @ | react-dom.js?ver=16.6.3:19111
  | interactiveUpdates | @ | react-dom.js?ver=16.6.3:2167
  | dispatchInteractiveEvent | @ | react-dom.js?ver=16.6.3:4979

**Comment by tn3rb** [comment]
This is because of some modifications I had done to fix a previous bug in `receiveEntityAndResolve()`. That has since been fixed in a different manner so my modifications were now resulting in new errors. Removing my modifications fixes things.
