### ISSUE TITLE
Fetching attendees for an event.

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#168]
### Is this a bug report?

* [ ] yes
* [x] no

Hi @nerrad 

You recently helped me with functionality to fetch attendees for an event. 
https://github.com/eventespresso/event-espresso-core/issues/159

I've been trying to use the first code you posted:
```
$where = array(
    'Registration.EVT_ID' => $post->ID,
    'ATT_email' => $current_user->user_email
);

$attendees = EEM_Attendee::instance()->get_all( array( $where ) );
/** @var EE_Attendee $attendee */
foreach ( $attendees as $attendee ) {
    //do your code here...
    $first_name = $attendee->fname();
    //etc.
    //to get the registrations attached to this attendee for this event
    /** @var EE_Registration[] $registrations */
    $registrations = $attendee->get_registrations(
        array(
            'EVT_ID' => $post->ID,
        )
    );
    foreach ( $registrations as $registration ) {
        //get answers
        $answers = $registration->answers();
        //loop through EE_Answer objects and display
    }
}
```

However it throws an error on `$attendee->get_registrations()`.

```
[12-Sep-2016 06:54:34 UTC] PHP Fatal error:  Uncaught exception 'EE_Error' with message 'You passed EVT_ID as a query parameter to EEM_Registration, which is illegal! The allowed query parameters are 0,limit,order_by,group_by,having,force_join,order,on_join_limit,default_where_conditions,caps' in /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php:2623
Stack trace:
#0 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php(821): EEM_Base->_create_model_query_info_carrier(Array)
#1 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php(723): EEM_Base->_get_all_wpdb_results(Array, 'ARRAY_A', NULL)
#2 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Soft_Delete_Base.model.php(63): EEM_Base->get_all(Array)
#3 /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_mo in /srv/www/projects-collaboration/kfsk/htdocs/wp-content/plugins/event-espresso-core-reg/core/db_models/EEM_Base.model.php on line 2623
```

I can't seem to figure out what to do.. Would be very grateful for some guidance :D

**Comment by nerrad** [comment]
Hey Jonathon,  $where conditions need to be added in their own array to the arguments to the model call (as index 0).  I made a mistake in my suggested code, it should be:

```
$registrations = $attendee->get_registrations(
	array(
		array(
			'EVT_ID' => $post->ID,
		)
	)
);
```

**Comment by jonathan-dejong** [comment]
Ah alright thanks! 
Seems to work :)
