### ISSUE TITLE
Fatal Error when using the Importer add-on while on /dev branch (EDTR)

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#3260]
Core branch: /dev
Importer add-on branch: Master

After activating the Importer add-on, click on the Importer menu item, this fatal error is thrown:

```
Fatal error: Uncaught RuntimeException: 
Invalid arguments supplied for the EventEspresso\core\libraries\rest_api\controllers\model\Read class,
1 were required but 0 were passed. 
in /core/EE_Registry.core.php:1264 

Stack trace: 
#0 /core/EE_Registry.core.php(773): EE_Registry->_create_object() 
#1 /core/services/loaders/CoreLoader.php(111): EE_Registry->create() 
#2 /core/services/loaders/Loader.php(83): EventEspresso\core\services\loaders\CoreLoader->load() 
#3 /core/services/loaders/Loader.php(94): EventEspresso\core\services\loaders\Loader->load() 
#4 /core/libraries/form_sections/inputs/EE_Select_Ajax_Model_Rest_Input.input.php(105): EventEspresso\core\services\loaders\Loader->getNew() 
#5 /var/w in /core/EE_Registry.core.php on line 1264
```

**Comment by tn3rb** [comment]
plz see: #3270

**Comment by tn3rb** [comment]
fixed and ready for testing

**Comment by garthkoyle** [comment]
I was able to activate the importer add-on master branch on rc.eventespresso.com which has the latest edtr/dev changes.
