### ISSUE TITLE
 Uncaught TijsVerkoyen\CssToInlineStyles\Exception: No HTML provided.

### ISSUE THREAD

**Issue by byron-roots** [eventespresso/event-espresso-core#3426]
**Describe the bug**
When sending out emails for event registration the sending fails and we get this error. `Uncaught TijsVerkoyen\CssToInlineStyles\Exception: No HTML provided`. 

**To Reproduce**
1. Go to default message template for Email Registration 
2. Test send email
3. Test fails and returns a 500 error

**Expected behavior**
Email should send with no errors

**Screenshots**

**Environment:**
 - Version of Event Espresso: Version 4.10.11.p
 - Version of WordPress: 5.6 and 5.7.2
 - Browser Latest chrome and safari
 - PHP Version 7.4.12

**Additional context**
```
[11-Jun-2021 11:39:35 UTC] PHP Fatal error:  Uncaught TijsVerkoyen\CssToInlineStyles\Exception: No HTML provided. in /Users/byron/Repositories/St-Barnabas-WP-Site/wp-content/plugins/event-espresso-core-reg/core/third_party_libs/cssinliner/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php:122
Stack trace:
#0 /Users/byron/Repositories/St-Barnabas-WP-Site/wp-content/plugins/wp-html-mail/includes/class-haet-mail.php(871): TijsVerkoyen\CssToInlineStyles\CssToInlineStyles->convert(true)
#1 /Users/byron/Repositories/St-Barnabas-WP-Site/wp-content/plugins/wp-html-mail/includes/class-haet-mail.php(850): Haet_Mail->inline_css('<!DOCTYPE html>...')
#2 /Users/byron/Repositories/St-Barnabas-WP-Site/wp-content/plugins/wp-html-mail/includes/class-haet-mail.php(543): Haet_Mail->prepare_email_for_delivery('<!DOCTYPE html>...')
#3 /Users/byron/Repositories/St-Barnabas-WP-Site/wp-includes/class-wp-hook.php(292): Haet_Mail->style_mail(Array)
#4 /Users/byron/Repositories/St-Barnabas-WP-Site/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
# in /Users/byron/Repositories/St-Barnabas-WP-Site/wp-content/plugins/event-espresso-core-reg/core/third_party_libs/cssinliner/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php on line 122
``` your original EE support forum thread
-->

**Comment by byron-roots** [comment]
As suggested from the support team adding the following filters fixes this issue

```
add_filter(
    'FHEE__EE_Email_messenger__apply_CSSInliner ',
    '__return_false'
);
```

**Comment by manzoorwanijk** [comment]
```php
add_filter(
    'FHEE__EE_Email_messenger__apply_CSSInliner',
    //                                        ^^ No space here
    '__return_false'
);
```
