### ISSUE TITLE
EDTR - Fix creating custom message templates

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3443]
Using Dev branch if you try to create a custom message template from within the event editor it fails.

To reproduce just click 'Create New Custom' on any message type in the notifications section of the event editor.

Give it a name and a description and click create. The ajax request will throw a fatal with this error:

```
[25-Jun-2021 09:09:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_messenger() on null in C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\admin_pages\messages\Messages_Admin_Page.core.php:2734
Stack trace:
#0 C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\admin_pages\messages\Messages_Admin_Page.core.php(1273): Messages_Admin_Page->_insert_or_update_message_template(true)
#1 C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\admin_pages\messages\Messages_Admin_Page.core.php(1288): Messages_Admin_Page->_add_message_template('payment', 'email', '1')
#2 C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\caffeinated\admin\extend\messages\espresso_events_Messages_Hooks_Extend.class.php(246): Messages_Admin_Page->add_message_template('payment', 'email', '1')
#3 C:\laragon\www\ee4editor\wp-includes\class-wp-hook.php(292): espresso_events_Messages_Hooks_Extend->create_new_custom('')
#4 C:\laragon\www\ee4editor\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
 in C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\admin_pages\messages\Messages_Admin_Page.core.php on line 2734
```

**Comment by tn3rb** [comment]
plz see #3453

**Comment by sethshoultes** [comment]
@Pebblo can you please confirm that this issue is fixed?

**Comment by Pebblo** [comment]
Yep, confirmed this is fixed.
