### ISSUE TITLE
Don't throw EntityNotFoundException for missing transactions for trashed Registrations

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#345]
See original Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11221

While testing [#11063](https://events.codebasehq.com/projects/event-espresso/tickets/11063) for EventSmart
Garth somehow managed to get a couple of his registrations trashed !?!?!

When viewing the registrations  in the Registrations Admin List table, the following error appeared:

```
Fatal error: Uncaught EventEspresso\core\exceptions\EntityNotFoundException:
The requested entity with Transaction ID="0" was not found. in
/core/db_classes/EE_Registration.class.php:1637

Stack trace:
#0 /admin_pages/registrations/EE_Registrations_List_Table.class.php(732): EE_Registration->transaction()
#1 /core/admin/EE_Admin_List_Table.core.php(733): EE_Registrations_List_Table->column_TXN_total(Object(EE_Registration))
#2 /core/admin/EE_Admin_List_Table.core.php(624): EE_Admin_List_Table->single_row_columns(Object(EE_Registration))
#3 /wp-admin/includes/class-wp-list-table.php(1180): EE_Admin_List_Table->single_row(Object(EE_Registration))
#4 /wp-admin/includes/class-wp-list-table.php(1165): WP_List_Table->display_rows()
#5 /wp-admin/includes/class-wp-list-table.php(1097): WP_List_T in /core/db_classes/EE_Registration.class.php on line 1637
```

likely need  to add a check that the registration is not trashed before throwing that exception.

**Comment by joshfeck** [comment]
It'd take more than just trashing some registrations for there to be no transaction. We'll leave this closed, but it can be reopened if there are some steps to replicate or there's another report beyond something that came up while testing something 2 years ago.
