### ISSUE TITLE
PHP8 Fatal error - EventEspresso\core\services\notifications\PersistentAdminNoticeManager::__construct(): Argument #2 ($capabilities_checker) must be of type EventEspresso\core\domain\services\capabilities\CapabilitiesChecker, null given

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3474]
Hey Brent,

If I switch to PHP8 (locally and one one of my 'live' test sites) I get this fatal:

```
[12-Jul-2021 21:02:25 UTC] PHP Fatal error:  
Uncaught TypeError: EventEspresso\core\services\notifications\PersistentAdminNoticeManager::__construct(): 
Argument #2 ($capabilities_checker) must be of type EventEspresso\core\domain\services\capabilities\CapabilitiesChecker, 
null given in \core\services\notifications\PersistentAdminNoticeManager.php:68

Stack trace:
#0 [internal function]:
    EventEspresso\core\services\notifications\PersistentAdminNoticeManager->__construct('', NULL, NULL)
#1 \core\EE_Registry.core.php(1262):
    ReflectionClass->newInstanceArgs(Array)
#2 \core\EE_Registry.core.php(773):
    EE_Registry->_create_object('EventEspresso\\c...', Array, '', false)
#3 \core\services\loaders\CoreLoader.php(111):
    EE_Registry->create('EventEspresso\\c...', Array, true, false, false, '')
#4 \core\services\loaders\CachingLoader.php(147):
    EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true)
#5 \core\services\loaders\Loader.php(82):
    EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true)
#6 \core\services\loaders\Loader.php(105):
    EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array)
#7 \core\services\request\RequestStackCoreApp.php(68):
    EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\\c...')
#8 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\RequestStackCoreApp->handleRequest()
#9 \core\services\request\middleware\BotDetector.php(36):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#10 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\middleware\BotDetector->handleRequest()
#11 \core\services\request\middleware\DetectFileEditorRequest.php(36):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#12 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\middleware\DetectFileEditorRequest->handleRequest()
#13 \core\services\request\middleware\PreProductionVersionWarning.php(33):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#14 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\middleware\PreProductionVersionWarning->handleRequest()
#15 \core\services\request\middleware\RecommendedVersions.php(49):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#16 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\middleware\RecommendedVersions->handleRequest()
#17 \core\services\request\middleware\DetectLogin.php(40):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#18 \core\services\request\middleware\Middleware.php(72):
    EventEspresso\core\services\request\middleware\DetectLogin->handleRequest()
#19 \core\services\request\middleware\SetRequestTypeContextChecker.php(55):
    EventEspresso\core\services\request\middleware\Middleware->processRequestStack()
#20 \core\services\request\RequestStack.php(59):
    EventEspresso\core\services\request\middleware\SetRequestTypeContextChecker->handleRequest()
#21 \core\services\bootstrap\BootstrapCore.php(187):
    EventEspresso\core\services\request\RequestStack->handleRequest()
#22 \core\services\bootstrap\BootstrapCore.php(109):
    EventEspresso\core\services\bootstrap\BootstrapCore->runRequestStack()
#23 \wp-includes\class-wp-hook.php(292):
    EventEspresso\core\services\bootstrap\BootstrapCore->initialize('')
#24 \wp-includes\class-wp-hook.php(316):  WP_Hook->apply_filters(NULL, Array)
#25 \wp-includes\plugin.php(484): WP_Hook->do_action(Array)
#26 \wp-settings.php(423): do_action('plugins_loaded')
#27 \wp-config.php(106): require_once('C:\\laragon\\www\\...')
#28 \wp-load.php(37): require_once('C:\\laragon\\www\\...')
#29 \wp-admin\admin-ajax.php(22): require_once('C:\\laragon\\www\\...')
#30 {main}
thrown in \core\services\notifications\PersistentAdminNoticeManager.php on line 68
```

I tested this with only EE and Debug bar enabled and still get the same fatal. Switch to PHP7 and it works as expected.

I don't currently run a site permanently on PHP8 but switch every now and again, I think this is a relatively new change. I've used PHP8 within the past couple of weeks on the live site and it didn't fatal like this, however switching back to older tags doesn't seem to be helping.

**Describe the bug**
Switch to PHP 8, some requests show the above fatal in the admin. Refresh the page and it loads, refresh again, fatal again.

**Comment by Pebblo** [comment]
So, we've just had a report come in of this happening on PHP7.3.6 so I'm bumping this to get some eyes on in case in case this is indeed a bigger issue.
