### ISSUE TITLE
Fix ticket selector embed code throwing fatal error

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3598]
If you use an events ticket selector embed code you'll get a fatal when viewing it:

```
[18-Nov-2021 16:01:40 UTC] PHP Fatal error: Uncaught ArgumentCountError: 
Too few arguments to function EventEspresso\modules\ticket_selector\DisplayTicketSelector::__construct(), 
0 passed and at least 2 expected in /modules/ticket_selector/DisplayTicketSelector.php:97

Stack trace:
#0 [internal function]: EventEspresso\modules\ticket_selector\DisplayTicketSelector->__construct()
#1 /core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array)
#2 /core/EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\m...', Array, '', false)
#3 /core/services/loaders/CoreLoader.php(111): EE_Registry->create('EventEspresso\\m...', Array, false, false, false, '')
#4 /core/services/ in /modules/ticket_selector/DisplayTicketSelector.php on line 97
```

To reproduce edit an event and click the 'Embed Ticket Selector' button just under the permalink.

Add that to a page in text mode (or HTML block).

View the page.

**Comment by Pebblo** [comment]
Or... another quick way to test, just visit the embed URL directly:

`{domain}/?event=XXXX&ticket_selector=iframe`
