### ISSUE TITLE
Waitlist - Uncaught TypeError: Argument 2 passed toWaitListForm::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3615]
Posting this in core for now as the fatal is due to changes from 4.10.14+ but I suspect this may also need an update for the add-on.

If you have a waitlist enabled on an event with expired tickets you'll now get the above fatal.

To reproduce you need an event with an upcoming/active DateTime and the ticket(s) are sold out and also expired.

In Event Espresso -> Events -> Templates -> Ticket selector template settings, set 'Show Expired Tickets' to true.

With 4.10.13.p you'll see an option to sign up to the waitlist (Note thatalthoug the option is shown, it wont actually work as there are no 'preferred option' section, see [HERE](https://monosnap.com/file/XSkjS1X4p0iVvzGNb8YtWizIpwqheE))

With master you'll get a fatal error like this:

```
[25-Nov-2021 10:35:34 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to EventEspresso\WaitList\domain\services\forms\WaitListForm::__construct() must be of the type array, null given in C:\laragon\www\ee4\wp-content\plugins\eea-wait-lists\domain\services\forms\WaitListForm.php:55
Stack trace:
#0 [internal function]: EventEspresso\WaitList\domain\services\forms\WaitListForm->__construct(Object(EE_Event), NULL, Object(EventEspresso\WaitList\domain\services\event\WaitListEventMeta), Object(EE_Registration_Config))
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array)
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\W...', Array, '', false)
#3 C:\laragon\www\ee4\wp-content\plugins\eea-wait-lists\domain\services\forms\WaitListFormHandler.php(97): EE_Registry->create('EventEspresso\\W...', Array)
#4 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\librari in C:\laragon\www\ee4\wp-content\plugins\eea-wait-lists\domain\services\forms\WaitListForm.php on line 55
```

**Comment by tn3rb** [comment]
that's really odd, because the `$tickets` variable passed to the `WaitListForm` is type cast as an array:

```php
        $tickets = (array) apply_filters(
            'FHEE__EventEspresso_WaitList_domain_services_forms__WaitListFormHandler__generate__tickets',
            $tickets,
            $active_tickets,
            $this->event
        );
        return $this->registry->create(
            'EventEspresso\WaitList\domain\services\forms\WaitListForm',
            array($this->event, $tickets)
        );
```

so even if the original query returned null, the return value from that filter is type cast to an array, so the  `WaitListForm`  should have received `[null]` (ie: `[]`)

will look into this some more to see if I can find anything that would cause something else to happen

**Comment by tn3rb** [comment]
Not able to recreate this issue locally, here's what I did:

- created a new event with an upcoming date and two tickets:

    - ticket 1 had a future sell until date (Nov 26) and a qty of 1

    - ticket 2 had a sell until date in the past (Oct 31)

- registered for the 1 available ticket for the event so that the event was sold out

- returned to the event listing to verify event status
      <img width="407" alt="Screenshot 2021-11-26 130634" src="https://user-images.githubusercontent.com/1751030/143653273-9c64cf41-2182-449c-ba23-b72159b13202.png">

- and to verify presence of Wait List form
  <img width="292" alt="Screenshot 2021-11-26 130651" src="https://user-images.githubusercontent.com/1751030/143653947-a9957567-bd53-43b8-8b20-4f7c7f5f3ad0.png">
 
- returned to event editor and changed ticket 1's sell until date (Nov 26) 
   <img width="422" alt="Screenshot 2021-11-26 130616" src="https://user-images.githubusercontent.com/1751030/143652358-2632ed63-168b-4452-b75e-025bbed182e3.png">
   to also be in the past (Oct 31)
   <img width="423" alt="Screenshot 2021-11-26 130815" src="https://user-images.githubusercontent.com/1751030/143654462-409cd085-5b7b-4fc5-b724-b9599728f2c6.png">

- refreshed event listing to verify tickets but Wait List sign up button does not appear at all
   <img width="396" alt="Screenshot 2021-11-26 130840" src="https://user-images.githubusercontent.com/1751030/143655350-4d6ccfa8-6d1c-4279-8cb8-7c3556e48f39.png">
  
- no errors appeared on screen or in my error logs

- as you can see in the last picture, expired tickets are set to be displayed


Can you plz investigate some more plz and see if there is another setting that is contributing to this issue?
