### ISSUE TITLE
Possible PHP8.1 issue with messages -  Uncaught RuntimeException: Called current() on invalid iterator

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3948]
Reported here: https://eventespresso.com/topic/php-8-1-possible-bug/

First, I should note that I can't reproduce this. I've tested PHP8.0 and 8.1 and triggered messages with them in the same way the user reporting this is.... no issues on my servers.

In short, if they go to Event Espresso -> Registrations and retrigger messages using the icon: https://monosnap.com/file/sEglSqjJs1LbUo5eygt5G1QiAXJpVt

They get this:

```
Fatal error: Uncaught RuntimeException: Called current() on invalid iterator in /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Message_Repository.lib.php:266 Stack trace: 
#0 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Message_Repository.lib.php(266): SplObjectStorage->current() 
#1 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Messages_Generator.lib.php(145): EE_Message_Repository->current() 
#2 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Messages_Processor.lib.php(130): EE_Messages_Generator->generate() 
#3 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Messages_Processor.lib.php(101): EE_Messages_Processor->batch_generate_from_queue(Array, true) 
#4 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Messages_Queue.lib.php(475): EE_Messages_Processor->process_immediately_from_queue(Object(EE_Messages_Queue)) 
#5 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/modules/messages/EED_Messages.module.php(758): EE_Messages_Queue->initiate_request_by_priority() 
#6 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page.core.php(3970): EED_Messages::process_resend(Array) 
#7 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/admin_pages/registrations/Registrations_Admin_Page.core.php(3230): EE_Admin_Page->_process_resend_registration() 
#8 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page.core.php(1025): Registrations_Admin_Page->_resend_registration() 
#9 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page_CPT.core.php(1163): EE_Admin_Page->_route_admin_request() 
#10 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page.core.php(607): EE_Admin_Page_CPT->route_admin_request() 
#11 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page.core.php(231): EE_Admin_Page->_page_setup() 
#12 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/admin_pages/registrations/Registrations_Admin_Page.core.php(83): EE_Admin_Page->__construct(true) 
#13 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php(34): Registrations_Admin_Page->__construct(true) 
#14 [internal function]: Extend_Registrations_Admin_Page->__construct(true) 
#15 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#16 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/EE_Registry.core.php(784): EE_Registry->_create_object(‘Extend_Registra…’, Array, ”, false) 
#17 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/CoreLoader.php(111): EE_Registry->create(‘Extend_Registra…’, Array, true, false, false, ”) 
#18 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load(‘Extend_Registra…’, Array, true) 
#19 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load(‘Extend_Registra…’, Array, true) 
#20 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/Loader.php(105): EventEspresso\core\services\loaders\Loader->load(‘Extend_Registra…’, Array) 
#21 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page_Init.core.php(428): EventEspresso\core\services\loaders\Loader->getShared(‘Extend_Registra…’, Array) 
#22 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page_CPT_Init.core.php(25): EE_Admin_Page_Init->_initialize_admin_page() 
#23 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page_Loader.core.php(355): EE_Admin_Page_CPT_Init->do_initial_loads() 
#24 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin_Page_Loader.core.php(87): EE_Admin_Page_Loader->_get_installed_pages() 
#25 [internal function]: EE_Admin_Page_Loader->__construct(Object(EventEspresso\core\services\loaders\Loader)) 
#26 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#27 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/EE_Registry.core.php(784): EE_Registry->_create_object(‘EE_Admin_Page_L…’, Array, ”, false) 
#28 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/CoreLoader.php(111): EE_Registry->create(‘EE_Admin_Page_L…’, Array, true, false, false, ”) 
#29 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load(‘EE_Admin_Page_L…’, Array, true) 
#30 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load(‘EE_Admin_Page_L…’, Array, true) 
#31 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/services/loaders/Loader.php(105): EventEspresso\core\services\loaders\Loader->load(‘EE_Admin_Page_L…’, Array) 
#32 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/admin/EE_Admin.core.php(211): EventEspresso\core\services\loaders\Loader->getShared(‘EE_Admin_Page_L…’, Array) 
#33 /usr/www/users/fluxtg/wp-includes/class-wp-hook.php(307): EE_Admin->init(”) 
#34 /usr/www/users/fluxtg/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(”, Array) 
#35 /usr/www/users/fluxtg/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#36 /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/EE_System.core.php(1263): do_action(‘AHEE__EE_System…’) 
#37 /usr/www/users/fluxtg/wp-includes/class-wp-hook.php(307): EE_System->initialize_last(”) 
#38 /usr/www/users/fluxtg/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) 
#39 /usr/www/users/fluxtg/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#40 /usr/www/users/fluxtg/wp-settings.php(598): do_action(‘init’) 
#41 /usr/www/users/fluxtg/wp-config.php(79): require_once(‘/usr/www/users/…’) 
#42 /usr/www/users/fluxtg/wp-load.php(50): require_once(‘/usr/www/users/…’) 
#43 /usr/www/users/fluxtg/wp-admin/admin.php(34): require_once(‘/usr/www/users/…’) 
#44 {main} thrown in /usr/www/users/fluxtg/wp-content/plugins/event-espresso-core-reg/core/libraries/messages/EE_Message_Repository.lib.php on line 266
```

**Comment by tn3rb** [comment]
@Pebblo 

the line of code referenced in the above error no longer exists in that class.
It was some pointless code that I removed, since it merely called the same method on the parent class:

```php
    /**
     * @return EE_Message
     */
    public function current()
    {
        return parent::current();
    }
```

That was removed in  `4.10.33.p`  so ask the customer to upgrade their version of EE, as it's _possible_ that that was some how causing issues, although I'm really at a loss to see how.
