### ISSUE TITLE
WP User integration add-on: PHP 8 Issues

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#4051]
Reported here: https://eventespresso.com/topic/php-8-compatibility-status/#post-335669

Although this is an add-on issue I think the issue is from core so creating this here.

With PHP8 and the WP User integration add-on active go to

Event Espresso -> Registration Form -> User integration settings.

You'll get a critical error:

```
[20-Sep-2022 19:24:35 UTC] PHP Fatal error:  Uncaught Error: Unknown named parameter $admin_page_object in /event-espresso-core-reg/core/admin/EE_Admin_Page.core.php:1024
Stack trace:
#0 /event-espresso-core-reg/core/admin/EE_Admin_Page.core.php(783): EE_Admin_Page->_route_admin_request()
#1 /event-espresso-core-reg/core/admin/EE_Admin_Page_Init.core.php(226): EE_Admin_Page->route_admin_request()
#2 /home/pebbloco/public_html/ee4/wp-includes/class-wp-hook.php(307): EE_Admin_Page_Init->initialize_admin_page()
#3 /home/pebbloco/public_html/ee4/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#4 /home/pebbloco/public_html/ee4/wp-includes/plugin.php(476): WP_Hook->do_action()
#5 /home/pebbloco/public_html/ee4/wp-admin/admin.php(259): do_action()
#6 {main}
  thrown in /event-espresso-core-reg/core/admin/EE_Admin_Page.core.php on line 1024
```

**Comment by tn3rb** [comment]
plz create all PHP related issues on the Cafe monorepo from now on
