### ISSUE TITLE
Fix Level 2 maintenance mode causing fatal error from PrivacyPolicy.php

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#489]
**Describe the bug**
If you activate Level 2 maintenance mode by setting up a new site and activating an older version of EE and then switch to 4.9.62+ you'll get a fatal error:

```
Fatal error: Uncaught EE_Error: Event Espresso Level 2 Maintenance mode is active. That means EE can not run ANY database queries until the necessary migration scripts have run which will take EE out of maintenance mode level 2. Please inform support of this error. in D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php:2378 Stack trace: 
#0 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php(1080): EEM_Base->_do_wpdb_query('get_results', Array) 
#1 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php(954): EEM_Base->_get_all_wpdb_results(Array, 'ARRAY_A', NULL) 
#2 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Payment_Method.model.php(134): EEM_Base->get_all(Array) 
#3 D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\domain\services\admin\privacy\policy\PrivacyPolicy.php(65): EEM_Payment_Method->get_all_active('CART') 
#4 D:\xampp\htdocs\ee4 in D:\xampp\htdocs\ee4\wp-content\plugins\event-espresso-core-reg\core\db_models\EEM_Base.model.php on line 2378
```

The above happens if you trigger any migrations, so if you had an older version of the calendar active previously (but no longer use it), then activate the calendar with EE4 core v4.9.62+ you'll get a fatal so marking as critical.

**Comment by mnelson4** [comment]
created https://github.com/eventespresso/event-espresso-core/pull/490 to address this
