### ISSUE TITLE
Fatal error on WP4.5 - Call to undefined function EventEspresso\core\services\assets\get_user_locale()

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#508]
Currently master will give a fatal error on the plugins page when using WP 4.5:

```
Fatal error: Uncaught Error: Call to undefined function EventEspresso\core\services\assets\get_user_locale() in D:\xampp\htdocs\wp45\wp-content\plugins\event-espresso-core-reg\core\services\assets\I18nRegistry.php:237 Stack trace: 
#0 D:\xampp\htdocs\wp45\wp-content\plugins\event-espresso-core-reg\core\services\assets\I18nRegistry.php(181): EventEspresso\core\services\assets\I18nRegistry->getJedLocaleData('event_espresso') 
#1 D:\xampp\htdocs\wp45\wp-content\plugins\event-espresso-core-reg\core\services\assets\I18nRegistry.php(139): EventEspresso\core\services\assets\I18nRegistry->getJedLocaleDataForDomainAndChunk('ee-wp-plugins-p...', 'event_espresso') 
#2 D:\xampp\htdocs\wp45\wp-content\plugins\event-espresso-core-reg\core\services\assets\I18nRegistry.php(98): EventEspresso\core\services\assets\I18nRegistry->queueI18nTranslationsForHandle('ee-wp-plugins-p...')
#3 D:\xampp\htdocs\wp45\wp-includes\plugin.php(235): EventEspresso\core\services\assets\I18nRegistry->queueI18n(Array)
#4 D:\xampp\htdocs\wp45\wp-includes\class.wp-s in D:\xampp\htdocs\wp45\wp-content\plugins\event-espresso-core-reg\core\services\assets\I18nRegistry.php on line 237
```

This is a clean install using WP 4.5.14

**Comment by sethshoultes** [comment]
@Pebblo is this something you can fix? If not, please pass along to @mnelson4.

**Comment by joshfeck** [comment]
I tested this locally on a site with WP 4.5 and this branch resolves the issue for me.
