### ISSUE TITLE
Promotions end point throwing a fatal error

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#630]
Reported here: https://eventespresso.com/topic/getting-internal-server-error-500-when-querying-promotions/

**Describe the bug**
If you navigate to the rest api promotions endpoint:

/wp-json/ee/v4.8.36/promotions

You'll get a fatal error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getTimezone() on null in /wp-content/plugins/event-espresso-core-reg/core/libraries/rest_api/controllers/model/Read.php:691
Stack trace:
#0 /wp-content/plugins/event-espresso-core-reg/core/libraries/rest_api/controllers/model/Read.php(579): EventEspresso\core\libraries\rest_api\controllers\model\Read->createBareEntityFromWpdbResults(Object(EEM_Promotion), Array)
#1 /wp-content/plugins/event-espresso-core-reg/core/libraries/rest_api/controllers/model/Read.php(360): EventEspresso\core\libraries\rest_api\controllers\model\Read->createEntityFromWpdbResult(Object(EEM_Promotion), Array, Object(WP_REST_Request))
#2 /wp-content/plugins/event-espresso-core-reg/core/libraries/rest_api/controllers/model/Read.php(84): EventEspresso\core\libraries\rest_api\controllers\model\Read->getEntitiesFromModel(Object(EEM_Promotion), Object(WP_REST_Request))
#3 /wp-content/plugins/event-espresso-core-reg/core/libraries/rest_api/controllers/model/Read.php on line 691
```
(Note you'll need to be authenticated)

**Additional context**
This is an issue with promotions, however the REST API is in core so I think this should be here?

**Comment by joshfeck** [comment]
Some additional info in case it's helpful to know:

If you send a request for the promotion via the line item you get a similar error:
e.g.
/wp-json/ee/v4.8.36/transactions/2037/line_items

error logged is:
```
PHP Fatal error:  Uncaught Error: Call to a member function getTimezone() on null in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php:691
Stack trace:
#0 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php(579): EventEspresso\core\libraries\rest_api\controllers\model\Read->createBareEntityFromWpdbResults(Object(EEM_Promotion), Array)
#1 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php(451): EventEspresso\core\libraries\rest_api\controllers\model\Read->createEntityFromWpdbResult(Object(EEM_Promotion), Array, Object(WP_REST_Request))
#2 /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php(512): EventEspresso\core\libraries\rest_api\controllers\model\Read->getEntitiesFromRelationUsingModelQueryParams(Array, Object(EE_Belongs_To_Any_Relation), Object(WP_REST_Request))
#3 in /srv/www/wordpress-default/public_html/wp-content/plugins/32-core/core/libraries/rest_api/controllers/model/Read.php on line 691
```

**Comment by mnelson4** [comment]
thanks guys, I see this only comes up if there is a null date...

**Comment by sethshoultes** [comment]
Quick fix?

**Comment by mnelson4** [comment]
probably

**Comment by mnelson4** [comment]
this was fixed in EE core (so Tony's suspicions that this was an EE core issue, not a promotions issue, were correct). PR was merged in.
